package com.homecanvas.iot.model;

import jakarta.persistence.*; // entity mapping is mapped to database tables
import lombok.AllArgsConstructor; // generates a constructor with 1 parameter
// for each field in the class whch is not initialized with a default value
import lombok.Data; // generates getters, setters, toString, equals, and hashCode methods
import lombok.NoArgsConstructor; // generates a no-argument constructor
import com.homecanvas.auth.model.User;
import java.time.LocalDateTime;

@Entity
@Table(name = "devices")
@Data
@NoArgsConstructor // generates a no-argument constructor which does not take any 
// parameters and initializes the object with default values
@AllArgsConstructor // generates a constructor with 1 parameter for each field in 
// the class which is not initialized with a default value
public class Device {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id; // primary key, auto-generated by the database when a new device is created

    @ManyToOne(fetch = FetchType.LAZY, optional = true) // many devices can belong to one user, and the user data
    // is loaded lazily. Owner can be null for auto-registered devices until claimed by a user.
    @JoinColumn(name = "owner_id", nullable = true) // foreign key column "owner_id" in the "devices"
    // table, CAN be null to allow auto-register devices before user claims them 
    private User owner;

    @Column(unique = true, nullable = false, length = 17)
    private String macAddress; // unique MAC address of the device, required for identifying devices during 
    // telemetry ingestion and for device registration 

    @Column(nullable = false)
    private String name; // user-friendly name for the device, required for display in the dashboard and for user interaction

    @Column(name = "last_seen")
    private LocalDateTime lastSeen;

    @Column(name = "created_at")
    private LocalDateTime createdAt = LocalDateTime.now();

    // Last command fields: store the most recent command from dashboard for device to retrieve
    @Column(name = "last_command_fan_on")
    private Boolean lastCommandFanOn; // store the last command for fan state (on/off) sent from the dashboard to the 
    // device, allowing the device to retrieve and execute the latest command when it checks in. This field is a Boolean, 
    // where true indicates the fan should be turned on, and false indicates it should be turned off.

    @Column(name = "last_command_led_on")
    private Boolean lastCommandLedOn;

    @Column(name = "last_command_lcd_message", length = 16)
    private String lastCommandLcdMessage;

    @Column(name = "last_command_servo_angle")
    private Integer lastCommandServoAngle;

    @Column(name = "last_command_at")
    private LocalDateTime lastCommandAt;

    // Constructor without id and lastSeen, as these are auto-generated and managed by the system
    public Device(User owner, String macAddress, String name) {
        this.owner = owner;
        this.macAddress = macAddress;
        this.name = name;
    }

}
